config/routes.rb
Rails.application.routes.draw do
  root 'hello#index'
  get 'resume', to: 'hello#resume'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/hello/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">jHolmes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to '<i class="fas fa-home"></i> Home'.html_safe, root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '<i class="fas fa-file"></i> Resume'.html_safe, resume_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="mailto:holmes.johnd@gmail.com"><i class="fas fa-envelope"></i> E-mail</a>
      </li>
      <li class="nav-item">
        <span class="nav-link"><i class="fas fa-mobile-alt"></i> 780 909 2364</span>
      </li>
    </ul>
  </div>
</nav>

app/views/hello/index.html.erb
<div class="container">
  <div class="jumbotron bg-white text-center">
      <h1 class="display-1"><b>John Holmes</b></h1>
      <h2 class="display-3">Software Developer</h2>
      <p class="lead">I'm a software developer based out of Edmonton, Alberta.</p>
  </div>
  <div class="d-flex">
    <ul class="list-inline mx-auto justify-content-center contact-links">
      <li class="list-inline-item text-center"><a href="https://www.linkedin.com/in/johnholmesyeg/"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
      <li class="list-inline-item text-center"><a href="https://github.com/pepper-roni"><i class="fab fa-github"></i> GitHub</a></li>
      <li class="list-inline-item text-center"><%= link_to '<i class="fas fa-file"></i> Resume'.html_safe, resume_path %></li>
      <li class="list-inline-item text-center"><a href="mailto:holmes.johnd@gmail.com"><i class="fas fa-envelope"></i> E-mail</a></li>
    </u>
  </div>
</div>

app/views/hello/resume.html.erb
<div class="container">
  <h1 class="display-3">Resume</h1>
  <p class="lead">I love learning new things which makes programming and computers so fascinating, there is always a new technology to learn, always a better way of doing things.</p>
  <h2 class="border-bottom">Work Experience</h2><br>
    <h5>
    Software Developer
    <small class="text-muted">We Know Training | March 2021 - Present</small>
    </h5>
    <p>Development on RapidLMS. Working with latest rails stack and an Angular front end.</p>
  <h5>
    Software Developer
    <small class="text-muted">Yardstick | January 2019 - March 2021</small>
  </h5>
  <p>Working on the Yardstick Measure high stakes testing platform. Ruby, Rails, and AngularJS.</p>
  <h5>
    Quality Assurance
    <small class="text-muted">Yardstick | January 2015 - January 2019</small>
  </h5>
  <p>Involved with testing of Yardstick's three major software platforms.</p>
  <ul>
    <li>test automation with RSpec and Selenium</li>
    <li>deployment and release management</li>
  </ul>
  <h5>
    Customer Support Specialist
    <small class="text-muted">Yardstick | January 2012 - January 2015</small>
  </h5>
  <p>Client onboarding and high stakes administration support and QA.</p>
  <h2 class="border-bottom">My Skills</h2><br>
  <dl class="row">
    <dt class="col-sm-3">Ruby</dt>
    <dd class="col-sm-9">Along with it's best friend Rails. I have some experience with GraphQL based API's. I also have some light experience with C# and Adobe Coldfusion</dd>

    <dt class="col-sm-3">Javascript</dt>
    <dd class="col-sm-9">Experience with ES6 and Angular.</dd>

    <dt class="col-sm-3">HTML & CSS</dt>
    <dd class="col-sm-9">Additionally some experience with Bootstrap and Sass.</dd>

    <dt class="col-sm-3">Databases</dt>
    <dd class="col-sm-9">Postgres and MS-SQL. Experience with Redis, MongoDB, and Elastic Search.</dd>

    <dt class="col-sm-3">Infrastructure</dt>
    <dd class="col-sm-9">Docker and some experience with Kubernetes.</dd>

    <dt class="col-sm-3">Tools</dt>
    <dd class="col-sm-9">Jira, Semaphore CI, Jenkins</dd>
  </dl>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav' %>
    <%= yield %>
  </body>
</html>